# Generated by Django 4.2.19 on 2025-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('choice_x', models.CharField(max_length=30)),
                ('choice_y', models.CharField(max_length=30)),
                ('choice_z', models.CharField(max_length=30)),
                ('votes_choice_x', models.IntegerField(default=0)),
                ('votes_choice_y', models.IntegerField(default=0)),
                ('votes_choice_z', models.IntegerField(default=0)),
            ],
        ),
    ]
